version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=saqib
      - POSTGRES_PASSWORD=password
      - POSTGRE_DB=ecommers
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8080:80'
    depends_on:
      - db


volumes:
  postgres_data: